swagger_testing/swagger_testing/urls.py
from django.contrib import admin
from django.urls import path, include

from app.views import URLProcessingView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', URLProcessingView.as_view(), name='main_view'),
]

swagger_testing/app/forms.py
from django import forms

class URLProcessingForm(forms.Form):
    swagger_url = forms.URLField(label='Enter a URL', help_text='e.g. https://petstore.swagger.io/v2/swagger.json')

swagger_testing/app/views.py
from django.contrib import messages
from django.shortcuts import render
from django.views import View
from app.forms import URLProcessingForm
from app.utils import swagger_test

class URLProcessingView(View):
    template_name = 'main.html'

    def get(self, request):
        form = URLProcessingForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = URLProcessingForm(request.POST)
        if form.is_valid():
            swagger_url = form.cleaned_data['swagger_url']
            swagger_test(app_url=swagger_url, request=request)
            return render(request, self.template_name, {'form': form})
        else:
            messages.error(request, f"Please enter a valid URL.")
            return render(request, self.template_name, {'form': form})

swagger_testing/app/templates/main.html
<!DOCTYPE html>
<html>
<head>
    <title>URL Processing</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 20px;
        }

        h1 {
            color: #333;
        }

        form {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"] {
            padding: 5px;
            width: 400px;
        }

        button[type="submit"] {
            padding: 5px 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }

        h2 {
            color: #333;
            margin-top: 20px;
        }

        ul {
            margin: 0;
            padding: 0;
            list-style-type: none;
        }

        li {
            margin-bottom: 5px;
        }

        .container {
          background-color: #f1f1f1;
          padding: 20px;
        }

        .messages {
          background-color: #fff;
          border: 1px solid #ccc;
          border-radius: 5px;
          padding: 10px;
        }

        .messages ul {
          list-style-type: none;
          padding: 0;
        }

        .message {
          margin-bottom: 10px;
          padding: 10px;
          border-radius: 5px;
        }

        .success {
          background-color: #dff0d8;
          color: #3c763d;
        }

        .error {
          background-color: #f2dede;
          color: #a94442;
        }

        .warning {
          background-color: #fcf8e3;
          color: #8a6d3b;
        }
        .container {
            background-color: #f1f1f1;
            padding: 20px;
        }

        .form-row {
            display: flex;
            align-items: center;
        }

        .form-group {
            margin-right: 10px;
        }

        button[type="submit"] {
            padding: 5px 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            cursor: pointer;
        }



    </style>
</head>
<body>
    <h1>Test Swagger Json</h1>

    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group">
                    <label for="id_swagger_url">{{ form.swagger_url.label }}</label>
                    <input type="text" id="id_swagger_url" name="swagger_url" placeholder="{{ form.swagger_url.help_text }}">
                </div>
                <div class="form-group">
                    <button type="submit">Test</button>
                </div>
            </div>
        </form>
    </div>


    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

</body>
</html>